### ISSUE TITLE
Each binding does not work when inside a select

### ISSUE THREAD

**Issue by Owlbertz** [mateusmaso/handlebars.binding#16]
The following code will not render any `option` elements inside the `select`.

```html
<select>
    {{#each items bind=true}}
        <option value="{{value}}">{{name}}</option>
    {{/each}}
</select>
```

**Comment by mateusmaso** [comment]
can you describe the data structure (context) so I can debug this scenario?

**Comment by Owlbertz** [comment]
Hi, I created [this pen](https://codepen.io/Owlbertz/pen/ZrQzaL?editors=1010) that reproduces the image. My actual context is a bit more complex, but I guess this is a general problem as it also fails with the simple structure I used here.

**Comment by mateusmaso** [comment]
This is a very weird bug, I'll try to figure out what is happening and write a test for it.

**Comment by mateusmaso** [comment]
Well, this bug was very weird indeed. I figured out that some html elements such as the `select` don't allow [custom elements inside their own block](https://stackoverflow.com/questions/28835077/problems-using-a-select-tag-in-a-custom-element-with-a-content-tag). Please update your project & codepen to `0.4.0`. Now it should work just fine 🍺

**Comment by Owlbertz** [comment]
Works in the pen, will update the project as well. Thanks for the fast fix (again)!
